In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("covid.csv")
df

,Country/Region,Continent,Population,TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region,iso_alpha
0,USA,North America,3.311981e+08,5032179,NaN,162804.0,NaN,2576668.0,NaN,2292707.0,18296.0,15194.0,492.0,63139605.0,190640.0,Americas,USA
1,Brazil,South America,2.127107e+08,2917562,NaN,98644.0,NaN,2047660.0,NaN,771258.0,8318.0,13716.0,464.0,13206188.0,62085.0,Americas,BRA
2,India,Asia,1.381345e+09,2025409,NaN,41638.0,NaN,1377384.0,NaN,606387.0,8944.0,1466.0,30.0,22149351.0,16035.0,South-EastAsia,IND
3,Russia,Europe,1.459409e+08,871894,NaN,14606.0,NaN,676357.0,NaN,180931.0,2300.0,5974.0,100.0,29716907.0,203623.0,Europe,RUS
4,South Africa,Africa,5.938157e+07,538184,NaN,9604.0,NaN,387316.0,NaN,141264.0,539.0,9063.0,162.0,3149807.0,53044.0,Africa,ZAF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,Montserrat,North America,4.992000e+03,13,NaN,1.0,NaN,10.0,NaN,2.0,NaN,2604.0,200.0,61.0,12220.0,NaN,MSR
205,Caribbean Netherlands,North America,2.624700e+04,13,NaN,NaN,NaN,7.0,NaN,6.0,NaN,495.0,NaN,424.0,16154.0,NaN,
206,Falkland Islands,South America,3.489000e+03,13,NaN,NaN,NaN,13.0,NaN,0.0,NaN,3726.0,NaN,1816.0,520493.0,NaN,FLK
207,Vatican City,Europe,8.010000e+02,12,NaN,NaN,NaN,12.0,NaN,0.0,NaN,14981.0,NaN,NaN,NaN,Europe,VAT
208,Western Sahara,Africa,5.986820e+05,10,NaN,1.0,NaN,8.0,NaN,1.0,NaN,17.0,2.0,NaN,NaN,Africa,ESH

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Country/Region    209 non-null    str
 1   Continent         208 non-null    str
 2   Population        208 non-null    float64
 3   TotalCases        209 non-null    int64
 4   NewCases          4 non-null      float64
 5   TotalDeaths       188 non-null    float64
 6   NewDeaths         3 non-null      float64
 7   TotalRecovered    205 non-null    float64
 8   NewRecovered      3 non-null      float64
 9   ActiveCases       205 non-null    float64
 10  Serious,Critical  122 non-null    float64
 11  Tot Cases/1M pop  208 non-null    float64
 12  Deaths/1M pop     187 non-null    float64
 13  TotalTests        191 non-null    float64
 14  Tests/1M pop      191 non-null    float64
 15  WHO Region        184 non-null    str
 16  iso_alpha         209 non-null    str
dtypes: float64(12), int64(1), str(4)
memory usage: 27.9 KB

In [5]:
df.isna().sum()

Country/Region        0
Continent             1
Population            1
TotalCases            0
NewCases            205
TotalDeaths          21
NewDeaths           206
TotalRecovered        4
NewRecovered        206
ActiveCases           4
Serious,Critical     87
Tot Cases/1M pop      1
Deaths/1M pop        22
TotalTests           18
Tests/1M pop         18
WHO Region           25
iso_alpha             0
dtype: int64

In [6]:
df.dropna(subset=["Continent"],inplace=True)

In [7]:
def null():
    return df.isnull().sum()

In [8]:
null()

Country/Region        0
Continent             0
Population            0
TotalCases            0
NewCases            204
TotalDeaths          21
NewDeaths           205
TotalRecovered        4
NewRecovered        205
ActiveCases           4
Serious,Critical     87
Tot Cases/1M pop      0
Deaths/1M pop        21
TotalTests           17
Tests/1M pop         17
WHO Region           24
iso_alpha             0
dtype: int64

In [9]:
df.drop(columns=["NewCases"],inplace=True)

In [10]:
null()

Country/Region        0
Continent             0
Population            0
TotalCases            0
TotalDeaths          21
NewDeaths           205
TotalRecovered        4
NewRecovered        205
ActiveCases           4
Serious,Critical     87
Tot Cases/1M pop      0
Deaths/1M pop        21
TotalTests           17
Tests/1M pop         17
WHO Region           24
iso_alpha             0
dtype: int64

In [11]:
df.drop(columns=["NewDeaths"],inplace=True)

In [12]:
null()

Country/Region        0
Continent             0
Population            0
TotalCases            0
TotalDeaths          21
TotalRecovered        4
NewRecovered        205
ActiveCases           4
Serious,Critical     87
Tot Cases/1M pop      0
Deaths/1M pop        21
TotalTests           17
Tests/1M pop         17
WHO Region           24
iso_alpha             0
dtype: int64

In [13]:
df["TotalDeaths"]=df["TotalDeaths"].fillna(df["TotalDeaths"].median())

In [14]:
null()

Country/Region        0
Continent             0
Population            0
TotalCases            0
TotalDeaths           0
TotalRecovered        4
NewRecovered        205
ActiveCases           4
Serious,Critical     87
Tot Cases/1M pop      0
Deaths/1M pop        21
TotalTests           17
Tests/1M pop         17
WHO Region           24
iso_alpha             0
dtype: int64

In [15]:
df.dropna(subset=["TotalRecovered"],inplace=True)
df

,Country/Region,Continent,Population,TotalCases,TotalDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",Tot Cases/1M pop,Deaths/1M pop,TotalTests,Tests/1M pop,WHO Region,iso_alpha
0,USA,North America,3.311981e+08,5032179,162804.0,2576668.0,NaN,2292707.0,18296.0,15194.0,492.0,63139605.0,190640.0,Americas,USA
1,Brazil,South America,2.127107e+08,2917562,98644.0,2047660.0,NaN,771258.0,8318.0,13716.0,464.0,13206188.0,62085.0,Americas,BRA
2,India,Asia,1.381345e+09,2025409,41638.0,1377384.0,NaN,606387.0,8944.0,1466.0,30.0,22149351.0,16035.0,South-EastAsia,IND
3,Russia,Europe,1.459409e+08,871894,14606.0,676357.0,NaN,180931.0,2300.0,5974.0,100.0,29716907.0,203623.0,Europe,RUS
4,South Africa,Africa,5.938157e+07,538184,9604.0,387316.0,NaN,141264.0,539.0,9063.0,162.0,3149807.0,53044.0,Africa,ZAF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,Montserrat,North America,4.992000e+03,13,1.0,10.0,NaN,2.0,NaN,2604.0,200.0,61.0,12220.0,NaN,MSR
205,Caribbean Netherlands,North America,2.624700e+04,13,119.0,7.0,NaN,6.0,NaN,495.0,NaN,424.0,16154.0,NaN,
206,Falkland Islands,South America,3.489000e+03,13,119.0,13.0,NaN,0.0,NaN,3726.0,NaN,1816.0,520493.0,NaN,FLK
207,Vatican City,Europe,8.010000e+02,12,119.0,12.0,NaN,0.0,NaN,14981.0,NaN,NaN,NaN,Europe,VAT
208,Western Sahara,Africa,5.986820e+05,10,1.0,8.0,NaN,1.0,NaN,17.0,2.0,NaN,NaN,Africa,ESH

In [16]:
df["TotalTests"]=df["TotalTests"].fillna(df["TotalTests"].median())

In [25]:
null()

Country/Region       0
Continent            0
Population           0
TotalCases           0
TotalDeaths          0
TotalRecovered       0
ActiveCases          0
Serious,Critical     0
Tot Cases/1M pop     0
Deaths/1M pop        0
TotalTests           0
Tests/1M pop         0
WHO Region          24
iso_alpha            0
dtype: int64

In [18]:
df.drop(columns=["NewRecovered"],inplace=True)

In [20]:
df["Serious,Critical"]=df["Serious,Critical"].fillna(df["Serious,Critical"].median())

In [22]:
df["Deaths/1M pop"]=df["Deaths/1M pop"].fillna(df["Deaths/1M pop"].median())

In [24]:
df["Tests/1M pop"]=df["Tests/1M pop"].fillna(df["Tests/1M pop"].median())

In [36]:
df[["WHO Region","Continent","Country/Region"]].tail(30)

         WHO Region          Continent          Country/Region
179             NaN      North America            Sint Maarten
180        Americas      North America                 Bermuda
181             NaN               Asia                 Brunei
182        Americas      North America                Barbados
183             NaN      North America        Turks and Caicos
184          Africa             Africa              Seychelles
185          Europe             Europe                  Monaco
186  South-EastAsia               Asia                  Bhutan
187        Americas      North America     Antigua and Barbuda
188          Europe             Europe           Liechtenstein
189        Americas      North America                  Belize
190             NaN  Australia/Oceania        French Polynesia
191             NaN      North America  St. Vincent Grenadines
192             NaN      North America            Saint Martin
193             NaN               Asia                   Macao
194             NaN      North America                 Curaçao
195  WesternPacific  Australia/Oceania                    Fiji
196        Americas      North America             Saint Lucia
197  South-EastAsia               Asia             Timor-Leste
198        Americas      North America                 Grenada
199             NaN  Australia/Oceania           New Caledonia
200  WesternPacific               Asia                    Laos
201        Americas      North America                Dominica
202        Americas      North America   Saint Kitts and Nevis
203          Europe      North America               Greenland
204             NaN      North America              Montserrat
205             NaN      North America   Caribbean Netherlands
206             NaN      South America        Falkland Islands
207          Europe             Europe            Vatican City
208          Africa             Africa          Western Sahara

In [37]:
def country(a):
    if a=="North America" or a=="	South America":
        return "Americas"
    elif a=="Asia":
        return "South-EastAsia"
    elif a=="Europe":
        return "Europe"
    elif a=="Australia/Oceania":
        return "WesternPacific"   
    elif a=="Africa":
        return "Africa"

In [39]:
df["WHO Region"]=df["WHO Region"].fillna(df["Continent"].apply(country))

In [40]:
null()

Country/Region      0
Continent           0
Population          0
TotalCases          0
TotalDeaths         0
TotalRecovered      0
ActiveCases         0
Serious,Critical    0
Tot Cases/1M pop    0
Deaths/1M pop       0
TotalTests          0
Tests/1M pop        0
WHO Region          2
iso_alpha           0
dtype: int64

In [41]:
df.dropna(subset=["WHO Region"],inplace=True)

In [42]:
null()

Country/Region      0
Continent           0
Population          0
TotalCases          0
TotalDeaths         0
TotalRecovered      0
ActiveCases         0
Serious,Critical    0
Tot Cases/1M pop    0
Deaths/1M pop       0
TotalTests          0
Tests/1M pop        0
WHO Region          0
iso_alpha           0
dtype: int64